### ISSUE TITLE
Add new issue type, "Support".

### ISSUE THREAD

**Issue by ordavidil** [Gizra/productivity#136]
We should add it as a new option in the issues type list ***Support***.

**Comment by nader77** [comment]
Taking over this.

**Comment by nader77** [comment]
@ordavidil Deployed, Please check.

**Comment by ordavidil** [comment]
@nader77 
Looks great,  just a minor fix of padding issue:

![selection_528](https://cloud.githubusercontent.com/assets/5985683/11395108/bfdf556a-9371-11e5-9e36-3a4a557c6d6b.png)
![selection_529](https://cloud.githubusercontent.com/assets/5985683/11395110/c37fef90-9371-11e5-8e9c-f68731b011dd.png)
![selection_530](https://cloud.githubusercontent.com/assets/5985683/11395112/c63ec7ec-9371-11e5-9271-73d8680afa9c.png)

**Comment by ordavidil** [comment]
@nader77 
One more thing,
after you save this is the result:
![selection_531](https://cloud.githubusercontent.com/assets/5985683/11395187/510f44b4-9372-11e5-9c14-6e4febfea48f.png)

* Maybe it's better to add more columns to the element,***col-md-6*** does the work:

![selection_532](https://cloud.githubusercontent.com/assets/5985683/11395207/6552581c-9372-11e5-8e3a-b2f8b7ef36fd.png)

**Comment by nader77** [comment]
@ordavidil Fixes for smaller screens have been deployed, Please check.

**Comment by ordavidil** [comment]
Perfecto, grazie :-)
