### ISSUE TITLE
Enlarging issue tracking inputs

### ISSUE THREAD

**Issue by bitamar** [Gizra/productivity#163]
Let's make the issue title and project selector wider.
![gizra_-_tracking_form_and_readme_txt_-_circuit_-____sites_circuit_](https://cloud.githubusercontent.com/assets/2283680/11187437/1289b024-8c8f-11e5-9a10-688384321f1d.png)

**Comment by nader77** [comment]
@bitamar This is invalid now right ?

**Comment by bitamar** [comment]
Yes.
