### ISSUE TITLE
Replace login to time-tracking to Github

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#169]

**Comment by nader77** [comment]
@bricel I didn't update the URLs in the application before I transferred it to Gizra. Could you please update them and send me the `client ID` and `client secret` in private just to make sure they didn't change. 
Then I can deploy, Thanks.

**Comment by nader77** [comment]
I mean to the URL of the live application: `http://productivity.gizra.com/`

**Comment by bricel** [comment]
@nader77 You are admin on the project, you should be able to do it, let me know if not.

**Comment by nader77** [comment]
@bricel The application is under [Gizra](https://github.com/Gizra) I don't have the permissions to edit settings in the orginaization.

**Comment by bricel** [comment]
Try now.

**Comment by nader77** [comment]
Works, 10x.

**Comment by nader77** [comment]
Deployed, As a follow-up I will open an issue to fix some mistakes in `config.json` and add Pantheon's automatic integrations from Hedley.
