### ISSUE TITLE
Support multiple rate for projects

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#183]
![image](https://cloud.githubusercontent.com/assets/165644/11626161/49dc2bb4-9ce9-11e5-9fa5-d6c8515b89f0.png)

According to the type of work -> qa, management, development etc..

If the type is not set default to zero.

**Comment by nader77** [comment]
@bricel The way I see it we should add `multifield` to the Project entity which will contain the different type of rates in the project and the rate sum calculation will be done per issue from the issue type.

**Comment by bricel** [comment]
yes, lets discuss this.

**Comment by nader77** [comment]
@nirgn975 1st thing:
1. Remove the `Rate` field from Projects.
2. Add `multifield` to project to replace the rate field with: rate and type.
3. Export your changes to features.
4. Add module update to live.

**Comment by nirgn975** [comment]
@nader77 Finish all four of them. Next step?

**Comment by nader77** [comment]
@nirgn975 
1. Add more sub-fields inside the multifield:
  1. Scope
  2. Total hours
  3. Total days

2. Remove those fields from the bundle.

3. Change the module update function.

4. We need to change the project's view to display our changes:
![gizra_productivity](https://cloud.githubusercontent.com/assets/7369740/11784900/a07ccd40-a287-11e5-9c45-ead26e7e92bc.png)
  1. Remove what is marked with an x.
  2. Create a table:
      Type of rate | Rate | Scope | Total hours | Total days

**Comment by nader77** [comment]
@nirgn975 

Next we need to alter 2 functions.
1. The function calculating the total hours/days for each project.
2. The function which alerts project managers about hours logged in the project.

For the first one: We need to calculate only relevant hours which means do not include hours of the following types:
  1. Management.
  2. Non billable.

For the second one: We need to add to the email percentage per issue type, Which means we need to check if any of the types reached a threshold and send an email.

**Comment by nader77** [comment]
@nirgn975 
* [ ] Let's keep the global hours, scope, day, percentage fields.
* [ ] Alter field scope to be disabled and be calculated from the type scopes.
* [ ] Remove disable from percientege.

**Comment by nader77** [comment]
@bricel What are the type of rates we don't want to calculate in the logged hour and notify about ?
1. Management
2. Non billable

anything else ?

**Comment by bricel** [comment]
@nader77  Since we have a scope for all of them, we can calculate them all, meaning -> if you have 10% management, then notify me when this one reach 25/50/75%.. as well. So in general if there is a scope there is notification.
