### ISSUE TITLE
Work session improvements 

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#185]
* [x] Show only "Active" employees
* [ ] Switch the hour to separate boxes for each time unit
* [x] Add Auto Title
* [x] Employees & Project titles should be sorted by alphabetical order

![create_work_session___gizra_productivity](https://cloud.githubusercontent.com/assets/7068965/11651756/c444d254-9d9b-11e5-88b0-9aa9aea417a4.jpg)

**Comment by bitamar** [comment]
@OritGeron - I'm not sure about separating the hour input. Because it already behaves as three inputs; If you click in the minutes part for instance, it will mark both digits and will let you rewrite them.

**Comment by bitamar** [comment]
The rest of the points are handled in #187.

**Comment by bitamar** [comment]
I'm adding a field on the projects, specifying whether it should be referenced by work-sessions. Then we will only have a single project on the project select in the session form.

**Comment by nader77** [comment]
@bitamar Could you please deploy ?

**Comment by bitamar** [comment]
In live.

**Comment by nader77** [comment]
@OritGeron Please check and close if all is good.
