### ISSUE TITLE
Change default order for content view

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#186]
When filtering by Work Session, the order should be by date field and not time stamp
![content___gizra_productivity](https://cloud.githubusercontent.com/assets/7068965/11651950/50a115cc-9d9d-11e5-8244-6c141739301b.jpg)

**Comment by bitamar** [comment]
@OritGeron - I created a better view for work sessions: http://live-productivity.pantheon.io/admin/content/work-sessions which is also sorted by date.
