### ISSUE TITLE
Show issues and pull requests even when I did not pushed/commented

### ISSUE THREAD

**Issue by RoySegall** [Gizra/productivity#192]
I created a PR on the 5th, pushed a code on the 6h and then push again on the the 10th. productivity  showed me the same pr from the 5th through the 10th.

**Comment by bricel** [comment]
@RoySegall - This works as designed, What would you like to happen ?

**Comment by nader77** [comment]
@bricel I have fixed this, It really was showing pull requests on dates that there was no commits, just because it was checking for a range, I changed it to check only on the day specified in the request.

**Comment by nader77** [comment]
@RoySegall Deployed, Please check :)

**Comment by nader77** [comment]
Needs a fix, please don't check yet.

**Comment by nader77** [comment]
@RoySegall Check and close if all is well.
