### ISSUE TITLE
Tracking fails with firefox

### ISSUE THREAD

**Issue by bitamar** [Gizra/productivity#193]
![screen shot 2015-12-14 at 4 50 45 pm](https://cloud.githubusercontent.com/assets/2283680/11784049/ef3c77fa-a282-11e5-868a-513604514d0f.png)

**Comment by bitamar** [comment]
![screen shot 2015-12-14 at 4 53 54 pm](https://cloud.githubusercontent.com/assets/2283680/11784112/52f5b18a-a283-11e5-8c4a-bf65d211532f.png)

**Comment by nader77** [comment]
@bitamar Deployed, Please check.

**Comment by bitamar** [comment]
I'm unable to open the app in firefox now. Does it work for you?

**Comment by bitamar** [comment]
Ignore my previous comment. I forgot I turned-off javascript on my firefox.

**Comment by bitamar** [comment]
:fire::joy_cat: :+1:
