### ISSUE TITLE
EntityMetadataWrapperException: Invalid data value given

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#200]
Alert Name: Errors

Edit Alert

Alert Description:

Timespan: Dec 15 06:06:21 to Dec 15 06:11:21

Source Group(s): N/A

Query Terms: json.severity:<=3 NOT "api/ci-build-items"

Total Triggers: 1 Events | Show All

1 Recent Events:

 {
  "timestamp": 1450159713,
  "type": "restful",
  "ip": "84.109.90.88",
  "request_uri": "http://live-productivity.pantheon.io/api/tracking",
  "referer": "http://productivity.gizra.com/",
  "uid": "87",
  "message": "EntityMetadataWrapperException: Invalid data value given. Be sure it matches the required data type and format. in EntityDrupalWrapper-\u003eset() (line 736 of /srv/bindings/95fecc2afc924f648703ee36d2729728/code/profiles/productivity/modules/contrib/entity/includes/entity.wrapper.inc).",
  "severity": 3,
  "uuid": "productivity-live"
}

**Comment by bricel** [comment]
"timestamp": 1450107832,
  "type": "php",
  "ip": "84.109.90.88",
  "request_uri": "http://live-productivity.pantheon.io/api/v1.0/timewatch-punch",
  "referer": "http://live-productivity.pantheon.io/timewatch/",
  "uid": "80",
  "message": "Notice: Undefined index: type in RestfulFormatterTrackingCalendar-\u003earrangeByDate() (line 58 of /srv/bindings/95fecc2afc924f648703ee36d2729728/code/profiles/productivity/modules/custom/productivity_restful/plugins/formatter/tracking_calendar/RestfulFormatterTrackingCalendar.class.php).",
  "severity": 5,
  "uuid": "productivity-live"
}

**Comment by nader77** [comment]
PR #203 Handles the first error.
