### ISSUE TITLE
Export Project monthly reports

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#211]
At the moment the export to XLS is not working.
outcome below-
![project_monthly_report](https://cloud.githubusercontent.com/assets/7068965/11940487/b0a06088-a831-11e5-9d9f-da1976c29b2c.jpg)
We need to fix it as soon as possible.

Can we, somehow, export it to PDF?

**Comment by nader77** [comment]
@nirgn975 We need to do some changes to the monthly report, export and filters according to the new scopes that we have created in #202

**Comment by nader77** [comment]
https://gist.github.com/nader77/62c104a4a73a395fb250

**Comment by bricel** [comment]
@OritGeron - New report is now available, on the project page.
![image](https://cloud.githubusercontent.com/assets/165644/13101784/d04d018c-d551-11e5-963e-ddbb8e5dfa62.png)
