### ISSUE TITLE
Total SUM line missing from Monthly Report

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#220]
Last seen on October 2015..

![project_monthly_report___gizra_productivity](https://cloud.githubusercontent.com/assets/7068965/12232783/445945cc-b86a-11e5-93be-3eda10a38ee2.jpg)

![project_monthly_report___hiro_db_oct_2015_pdf](https://cloud.githubusercontent.com/assets/7068965/12232836/a8cd2ab4-b86a-11e5-9f48-9545d59e150a.jpg)

**Comment by bricel** [comment]
Nir is rewriting this page, so it should be fixed soon.
