### ISSUE TITLE
RestfulFormatterTrackingCalendar.class.php error from loggly

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#248]
```timestamp": 1458457693,
  "type": "php",
  "ip": "84.109.90.88",
  "request_uri": "http://live-productivity.pantheon.io/api/v1.0/timewatch-punch",
  "referer": "http://live-productivity.pantheon.io/timewatch/",
  "uid": "80",
  "message": "Notice: Undefined index: type in RestfulFormatterTrackingCalendar-\u003earrangeByDate() (line 58 of /srv/bindings/3e77f9bfa0174cd0ad701add26044179/code/profiles/productivity/modules/custom/productivity_restful/plugins/formatter/tracking_calendar/RestfulFormatterTrackingCalendar.class.php).",
  "severity": 5,
  "uuid": "productivity-live"
```

**Comment by bricel** [comment]
@Moo64c - I think we get this notice each time we use the ELM time watch.

**Comment by Moo64c** [comment]
@bricel 
Could not replicate - specifically, calling ``api/v1.0/timewatch-punch`` doesn't generate a request for the `RestfulFormatterTrackingCalendar` method in question . Bit confused to how that happened. Can you clarify?
Thanks.
Found some other problems & PR'd them for now.

**Comment by bricel** [comment]
@bitamar , Can you look at this.

**Comment by bitamar** [comment]
This one is very sneaky. I couldn't reproduce it locally, not on a clean installation and also not with the live database.

**Comment by bricel** [comment]
I have a suspect:
https://github.com/Gizra/productivity/blob/c83068d17cb9aa6a228f6e25cec7bc8fc37738fb/productivity/modules/custom/productivity_time_tracking/productivity_time_tracking.module#L103

Looks this is called from hook_element_info(), which i suspect is called on any request.

**Comment by bricel** [comment]
Some more debugging, trying to reproduce using live env failed, tried with real Ipad and Safari failed, reproduced only on Ipad + Chrome

**Comment by bricel** [comment]
ipad header difference cause this:
* ipad/chrome
```$GLOBALS['_SERVER']['HTTP_ACCEPT']="*/*,image/webp"```
* non  ipad/chrome
```$GLOBALS['_SERVER']['HTTP_ACCEPT']="*/*"```

**Comment by bricel** [comment]
here is some more info about the special header http://stackoverflow.com/questions/32287347/why-does-chrome-for-ios-insert-image-webp-content-type

**Comment by bricel** [comment]
Patch suggestion for restful 
https://github.com/RESTful-Drupal/restful/pull/889/files
