### ISSUE TITLE
Recalculate hours button bug.

### ISSUE THREAD

**Issue by nader77** [Gizra/productivity#260]
<img width="808" alt="gizra_productivity" src="https://cloud.githubusercontent.com/assets/7369740/14314191/22a52a98-fbf6-11e5-8612-f649e9169b2e.png">

@bricel The button is not re-calculating the hours in each scope, Only in the total scope.

**Comment by bricel** [comment]
@nader77 - Yes, this should be removed anyway after merging #247, the PR removes the need for that button, since Totals are recalculated on the fly.
