### ISSUE TITLE
Add a clock to the header

### ISSUE THREAD

**Issue by ordavidil** [Gizra/productivity#275]
@nader77 
Is it possible to add the time of the entrance/exit for each day ?

Somewhere around here (?) :
![selection_166](https://cloud.githubusercontent.com/assets/5985683/14948341/e799f724-1047-11e6-9b9f-76b0693bb812.png)

**Comment by nader77** [comment]
Should be easy to do, Good idea as well.

**Comment by nader77** [comment]
Not relevant anymore.
