### ISSUE TITLE
Add "Attendance" field in Summary 

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#301]
![monthly_employee_report___gizra_productivity](https://cloud.githubusercontent.com/assets/7068965/15853265/f1d6db22-2cac-11e6-8107-1b1f0ec75158.png)

**Comment by bricel** [comment]
@OritGeron - What number should I see in the Attendance ?  Same as total ? or total - Extra time ?

**Comment by bricel** [comment]
Like this ?
![image](https://cloud.githubusercontent.com/assets/165644/20641228/430f4c32-b3fc-11e6-916f-969fb90d5d8e.png)

**Comment by bricel** [comment]
Madaan
![image](https://cloud.githubusercontent.com/assets/165644/20641289/5b7333f0-b3fd-11e6-8bf4-3bd078f61664.png)

**Comment by OritGeron** [comment]
@bricel a word from Shaul - DO NOT TOUCH THE PREVIOUS CALCULATIONS!

1. **Attendance** should only be **ACTUAL** working hours + Conventions (work related)
2. These are the things that are _EXCLUDED_ from the Madan calculations (and needs to appear in the TOTAL)
- Miluim
- Vacations
- Sick days
- On duty abroad (Tafkid be'hul)

3. **TOTAL** - reflects attendance **+** absence (maybe it's better to replace "time off" with absence )

4. Madan total is ONLY madan related hours

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/27992392-78edb93c-649c-11e7-9301-81ec0c461ce0.png)
