### ISSUE TITLE
Outside people can register to productivity

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#317]
I blocked them

![people___gizra_productivity](https://cloud.githubusercontent.com/assets/7068965/17103624/e8100a5e-5287-11e6-992e-537a55b73a5b.jpg)

**Comment by AronNovak** [comment]
I implemented a draft fix for this, before proceeding with further tests, I'd like to validate the workflow on Gizra side of accepting a new account. Is it fine if the GitHub account first must be added to the organization and this login can be used only afterwards or do we want some kind of soft-blocking that they can still login but they are not able to do / see anything before they're added to the org? The first is easier to implement, that's the approach I followed.

**Comment by AronNovak** [comment]
I created the per-branch test site on Pantheon, the results are promising.
Via /devel/php, I could execute part of the snippet:
```
$data = array();
$data['login'] = 'AronNovak';
try {
dpm(variable_get('productivity_github_organization', 'Gizra'));
$url = 'orgs/' . variable_get('productivity_github_organization', 'Gizra') . '/members/' . $data['login'];
productivity_github_http_request($url, array(), FALSE);
dpm("exist");
}
catch (RestfulException $e) {
dpm($e);
dpm("do not exist");
}
```
And it gave the proper result:
```
Gizra

exist
```

So essentially the concept works. But if i do not pass access-token, like via devel/php, only public memberships can be requested. So now i continue to connect a local productivity frontend to this per-branch site on Pantheon, and altering my org visibility to test the access. Also I signed up for a non-member throw-away Github account to test the deny scenario: `JustATestAron`

**Comment by AronNovak** [comment]
I went further with testing. Obtained a personal access token from GitHub, I could simulate the real login scenarios via `/devel/php` that way, works as expected, private membership is correctly handled. W/o access token, private membership is not visible.

**Comment by ordavidil** [comment]
@AronNovak @bricel 
It seems that the login via GitHub is not working properly (I do know that I'm part of the organization :) )

![gizra_-_login](https://cloud.githubusercontent.com/assets/5985683/23174658/d26695ea-f865-11e6-9949-b0327357b232.gif)
