### ISSUE TITLE
solve "wrong pincode" error when using TimeWatch out-of-office

### ISSUE THREAD

**Issue by noamoss** [Gizra/productivity#342]
for about two week (mid December) getting the following on http://productivity-server.gizra.com/timewatch/ :
![image](https://cloud.githubusercontent.com/assets/3581741/21508627/24985526-cc8b-11e6-87aa-0a5101799b95.png)

no problem logging in office.

**Comment by liatsade** [comment]
This also happened to me several times, but then l tried from my mobile and it was ok.

**Comment by bitamar** [comment]
This happens when you're logged in on the backend with your user. You can avoid this for now by accessing the timewatch in incognito mode.
Related to #227 and #213

**Comment by noamoss** [comment]
@bitamar thanks. Closing to avoid duplication.
