### ISSUE TITLE
Issue type is missing for a saved track

### ISSUE THREAD

**Issue by ordavidil** [Gizra/productivity#346]
When loading an existing track the list of the issue type is empty:
![gizra_-_tracking_form_](https://cloud.githubusercontent.com/assets/5985683/21684209/74fa76e4-d365-11e6-8463-3c9185929d43.gif)

**Comment by bricel** [comment]
@ordavidil - this is not a bug, the list is now taken form the project on the backend, @OritGeron - please add DEV on C4D.

**Comment by ordavidil** [comment]
there is inconsistency between creating new project for tracking and edit an existing one.

**Comment by nader77** [comment]
I will have a look, I think there's a bug in the editing (not creation)

**Comment by nader77** [comment]
Deployed, Sorry @bricel this bug was bothering me :)
