### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by ordavidil** [Gizra/productivity#358]
@AronNovak @bricel 
It seems that the login via GitHub is not working properly (I do know that I'm part of the organization :) )

![gizra_-_login](https://cloud.githubusercontent.com/assets/5985683/23174658/d26695ea-f865-11e6-9949-b0327357b232.gif)

Seems related to #356

**Comment by AronNovak** [comment]
It will affect everybody with private membership, i just tried to toggle my account's visibility and i could reproduce the error. I will check ASAP if it means that we need to revert the whole hardening or we can make it work.

**Comment by bricel** [comment]
I reverted #356 for now.

**Comment by AronNovak** [comment]
And now this protection is handled in #366
