### ISSUE TITLE
Change timewatch project to Municipalities

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#362]

**Comment by nader77** [comment]
@bricel Changed ELM config and deployed to Pantheon:

![timewatch](https://cloud.githubusercontent.com/assets/7369740/23616816/a7a9466c-0293-11e7-98d6-4fbe11d0bad0.jpg)

**Comment by nader77** [comment]
@bricel The employees that used to login to the old project should continue with the new project ?

**Comment by bricel** [comment]
Thanks.
