### ISSUE TITLE
Login with GH to backend

### ISSUE THREAD

**Issue by bricel** [Gizra/productivity#365]
@AronNovak - maybe you can start with this. 

We want to be able to login with Github to the backend, since we are removing the front end.

**Comment by AronNovak** [comment]
There's an issue with existing users without OpenID, starting a new PR soon.

[2838172-support-existing-user-d7-reroll.txt](https://github.com/Gizra/productivity/files/865322/2838172-support-existing-user-d7-reroll.txt)

**Comment by AronNovak** [comment]
@bricel The PR above would only solve one of our issues, as you suggested, filling authmap table would make much more sense. I crafted a shell script that would allow us to write an update hook for this purpose:
```bash
#!/bin/bash

GH_FIELD=$(drush @productivity.live sqlq "select entity_id, field_github_username_value from field_revision_field_github_username")
IFS=$'\n'
for i in $GH_FIELD
do
  DRUPAL_UID=$(echo $i | cut -d$'\t' -f1)
  GH_NAME=$(echo $i | cut -d$'\t' -f2)
  GH_ID=$(curl -H "Authorization: token [PERSONAL_ACCESS_TOKEN_FROM_GH]" --silent https://api.github.com/users/"$GH_NAME" | grep \"id\"\: | grep -o "[0-9]\+")
  echo "INSERT INTO authmap (uid, authname, module) VALUES ($DRUPAL_UID, $GH_ID, 'openid_connect_github')"
done;
```

I am going to test it a bit, write an update hook, and configure a testable environment at Pantheon. Does this sound good?

**Comment by bricel** [comment]
@AronNovak - Deployed to live, I delete your duplicate user (the one created with GH email), can you check login works for you now.

Thanks.

**Comment by AronNovak** [comment]
Yes, thanks, the login works perfectly!
