### ISSUE TITLE
AngularJs frontend - Issue types fixes [2h]

### ISSUE THREAD

**Issue by nader77** [Gizra/productivity#367]
If a project have the same issue type twice but with different "labels", The AngularJs app shows only the first one:
![edit_project_mx1___live_gizra_productivity](https://cloud.githubusercontent.com/assets/7369740/23899113/899cd132-08bc-11e7-9159-a57797167db5.jpg)

![gizra_-_tracking_form](https://cloud.githubusercontent.com/assets/7369740/23899129/98a381ee-08bc-11e7-9bee-34a3bae47d18.jpg)

The type's label should be taken from the field "Work type display"

**Comment by bricel** [comment]
Closing this in favor of #277 and #357
