### ISSUE TITLE
Monthly report not showing hours recorded

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/productivity#380]
On JEP - findyoursummer - no hours show in monthly report after hours were recorded (retroactively)

![banners_and_alerts_and_issue_tracking_table___live_gizra_productivity](https://cloud.githubusercontent.com/assets/688507/24618360/6d765b36-185c-11e7-8fd7-b1b31594b033.png)

but for example: 

![banners_and_alerts_and_adam___live_gizra_productivity](https://cloud.githubusercontent.com/assets/688507/24618486/d4424258-185c-11e7-98c5-a3f81a5ab0b3.png)

**Comment by bricel** [comment]
Yes, this is because of the migration to the new format, This report has not been updated yet, I will try to finish it this week.

**Comment by IshaDakota** [comment]
👍 

so I shouldn't be billing clients based on this report then ;)

**Comment by bricel** [comment]
@IshaDakota - Just pushed first version of the report:
* New -http://productivity.gizra.com/monthly-report/38818/2017/3/true
* old is still available at http://productivity.gizra.com/monthly-report-old/38818/2017/3/true

**Comment by bricel** [comment]
Added missing labels.
![image](https://cloud.githubusercontent.com/assets/165644/24647687/910d2070-1929-11e7-919f-19c1eaadf26b.png)
