### ISSUE TITLE
Activities are marked as `development` type even though I select different type

### ISSUE THREAD

**Issue by liatsade** [Gizra/productivity#393]
@brice now I see that all my activities are marked as `development` even though I have marked them as `Training` or `Support`.  
I tried to change it and save, but when I refresh the page it  turn into `development` again.

![liat___live_gizra_productivity](https://cloud.githubusercontent.com/assets/20393485/25007781/4f0c2ac0-206a-11e7-95f3-c52ef084b73d.jpg)

**Comment by bricel** [comment]
It's my bad, there are ok behind the scene, will fix this soon.
