### ISSUE TITLE
Two bills for the same client/repo

### ISSUE THREAD

**Issue by noamoss** [Gizra/productivity#398]
One repo can be used under two different bills/projects in Productivity (i.e. not finishing first agreement while starting a retainer).

Because both Productivity projects are connected to the same repo, when adding hours, most of the time productivity chooses one of them and do not let the worker change the default selection:

![image](https://cloud.githubusercontent.com/assets/3581741/25137659/1293bff4-2461-11e7-8926-32462d51f10d.png)

**Comment by noamoss** [comment]
@nader77 spoke with @OritGeron about it today, please correct / update description if I missed something.

**Comment by bricel** [comment]
@noamoss @OritGeron - In case of (Lock project billing report upon Project completion) I will not let Developer/anymore  submit new hour on existing issue, which will require to open a new issue on a new project. OK ?

**Comment by OritGeron** [comment]
yes

**Comment by noamoss** [comment]
Ot is not as simple because it means we are losing track of the issue
original timebox tracking and will make a mess on the project board Issues
are not being closed or reported by calendar.

The best solution would be to enable an issue to be shared by two separate
bills/POs. It is a very common situation.


If not, I think the developers should see an indication and an instruction
message, asking then to open a follow up issue (or even better, let
productivty clone the issue into a new one (including box and actual time
spent on it).

**Comment by noamoss** [comment]
@bricel @OritGeron 

Thought about it. I guess we have this problem only with edge cases, like the current situation of Danel and UNFPA.

I can handle it, as long as far as an instruction message will appear to the developers: "Can't record this issue/PR, contact Account Manager for advice" - it will enable me to create a follow-up issue with the required Time box for the report. 

@bricel is it possible to set such a custom message?

**Comment by bricel** [comment]
@OritGeron @noamoss - Deployed, to set milestones tracking use this settings ->
![image](https://user-images.githubusercontent.com/165644/30806534-e0f6059e-a1fe-11e7-9167-4ab6bd20538d.png)

**Comment by noamoss** [comment]
@bricel can't get to the admin view to check it:

![image](https://user-images.githubusercontent.com/3581741/30846874-fa6f8ea2-a2a1-11e7-9ae9-7fa9d92409be.png)

checked both on Mx1 and Danel POs

**Comment by noamoss** [comment]
@bricel @OritGeron I pointed Mx1 and Danel POs to the relevant GH milestones. Will track and report by upcoming Sunday.

**Comment by noamoss** [comment]
still checking

@bricel @OritGeron please notice that to be able to connect a milestone to a new PO you need to make sure on Github:

1. The new Milestone was already defined.
2. At least 1 issue was assigned to the new milestone.

**Comment by noamoss** [comment]
seems to work, as far as I can tell. Closing issue.
