### ISSUE TITLE
Wrong timewatch total

### ISSUE THREAD

**Issue by bitamar** [Gizra/productivity#406]
On the 26/3,  I have three working sessions totalling to 5.07, but the monthly view shows 14:03

<img width="1548" alt="itamar___live_gizra_productivity_und_work_sessions___live_gizra_productivity_und_48_20_min_-_getting_ready_ _toggl" src="https://cloud.githubusercontent.com/assets/2283680/25327283/e372df58-28d3-11e7-837d-b4fa53f21969.png">

http://productivity.gizra.com/admin/content/work-sessions?field_session_date_value_op=between&field_session_date_value%5Bvalue%5D%5Bdate%5D=&field_session_date_value%5Bmin%5D%5Bdate%5D=26%2F03%2F2017&field_session_date_value%5Bmax%5D%5Bdate%5D=26%2F03%2F2017&uid=itamar

**Comment by bricel** [comment]
@bitamar - This is because you have a vacation day set for this day, and it adds 9 hours.

**Comment by bricel** [comment]
I fixed the view to show the vacation:

![image](https://cloud.githubusercontent.com/assets/165644/25331472/e4fc8c94-28eb-11e7-9e1a-9d0010e47e75.png)

**Comment by bricel** [comment]
I deleted the item, Note in you case no need to add vacations.

**Comment by bitamar** [comment]
Thanks!
