### ISSUE TITLE
Add SSL to productivity.gizra.com [1h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/productivity#415]
Via https://pantheon.io/docs/free-https/

**Comment by amitaibu** [comment]
👍 I'm assigning to you :)

**Comment by AronNovak** [comment]
So via Pantheon, we'd need to pay more, upgrade to pro, so it's a no-go, especially that this domain is already under CloudFlare:
![anonymous-item1](https://cloud.githubusercontent.com/assets/114076/26440532/0d1974b8-412d-11e7-8253-9c8a7a7304a3.png)

@bricel @amitaibu are we aware of any issues that would prevent us to proxy the traffic via CloudFlare and get free cert from them? I guess Friday is a good day to do an experiment, with significantly less users.

**Comment by bricel** [comment]
@AronNovak - it should work with CF proxy. just switch it and it looks ok.
![image](https://cloud.githubusercontent.com/assets/165644/26470054/f65a9c3e-41a4-11e7-92ac-b46b6339cfe1.png)

The only issue I know, is that some older browser wont support this type of SSL, which is a non issue for us.
