### ISSUE TITLE
Multiple rows for 1 PR.

### ISSUE THREAD

**Issue by nader77** [Gizra/productivity#417]
@bricel I don't know if this reported already but I'm seeing multiple entries on the same PR, one new line for each commit or comment I make in the PR:
![live_gizra_productivity](https://cloud.githubusercontent.com/assets/7369740/26032116/8cf4e87c-3893-11e7-8d4e-f0ad4506cede.jpg)

**Comment by bricel** [comment]
@nader77 Thanks, I pushed a fix today, let me know if you still see this after 12:00.

**Comment by bricel** [comment]
Follow up: check how TRUE value is return in $cache, see commit above.

**Comment by nader77** [comment]
Looks good.

**Comment by bricel** [comment]
Let's keep open for the follow up, since the fix was a patch that need to be replaced.
