### ISSUE TITLE
Switch between Time estimate and Actual time in detailed view

### ISSUE THREAD

**Issue by liatsade** [Gizra/productivity#421]
Actual time values display in `Time estimate` column (instead of `Actual time` column).

![unio_6_6_burn_table___live_gizra_productivity](https://cloud.githubusercontent.com/assets/20393485/26104036/d43ee298-3a44-11e7-9a8a-0c15caa60e5e.jpg)

**Comment by bricel** [comment]
Fixed.
![image](https://cloud.githubusercontent.com/assets/165644/26143645/71190464-3aee-11e7-90cc-b2c9267a0203.png)
