### ISSUE TITLE
Add chrome extension to integrate time tracking in the GitHub issue/ PR

### ISSUE THREAD

**Issue by amitaibu** [Gizra/productivity#423]
https://mixandgo.com/blog/writing-a-chrome-extension-with-elm

**Comment by bricel** [comment]
@amitaibu- when installing the ext, I get blank Iframe.
![image](https://cloud.githubusercontent.com/assets/165644/26484801/cc7ad778-41fc-11e7-8257-b3e1925d54a7.png)

**Comment by amitaibu** [comment]
Did you install the extension by drag&drop of the `chrome-extension` folder to your `chrome://extensions`?

I'm also seeing a blank, page but I think it might be related to https://github.com/Gizra/productivity/issues/427 . For example if you will change [url](https://github.com/Gizra/productivity/blob/7cbfba17837abeb5efae7a5466adb40292dc5195/chrome-extension/frame.js#L5) to be `"https://shoov.io"`, and refresh the `chrome://extensions` page -- you should be able to see it properly.
