### ISSUE TITLE
Allow login via SSL [3h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/productivity#427]
Trying to load scripts via `http` (AFAIK this can also be "fixed" via CloudFlare)

![window_and_user_account___live_gizra_productivity](https://cloud.githubusercontent.com/assets/125707/26497807/70f7b66c-4235-11e7-87b3-cb79393b3607.jpg)

Also, I think the login via GitHub should change on GitHub's side, to point back to the `https://`, otherwise we get `http://productivity.gizra.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=vej1pZNqSZatcjQpAqeK7OFVQkRyi3q9AWZ2rXeOsZg`

At the same time, we should probably auto redirect from http to https

**Comment by AronNovak** [comment]
Ok, very first, I fix the GitHub issue, otherwise we lock out ourselves.
The HTTPS-only can be solved by CloudFlare rules.

**Comment by AronNovak** [comment]
@bricel for fixing the HTTPS login itself, i'd need to edit the application at GitHub, to fix the registered callback URL. If i receive access via LastPass, i can go ahead on my own. Thanks!

**Comment by bricel** [comment]
@AronNovak - I gave you admin role on GH.

**Comment by AronNovak** [comment]
@bricel Thanks! I tried out quickly, so far I could not locate the app on the GH UI that's owned by Gizra  org, i will see if it'd doable. Is it supped to show up under:
![pdf1](https://cloud.githubusercontent.com/assets/114076/26519501/4919c09e-42c2-11e7-9ac4-39cfaad8fa7f.png)

?

**Comment by amitaibu** [comment]
unsafe resources loading handled in https://github.com/Gizra/productivity/pull/428

**Comment by amitaibu** [comment]
@AronNovak I've changed the app settings. So now if you try to login form `http` you will get an error. Only login for `https` works now.

This means, we need to redirect from `http` to `https`

**Comment by AronNovak** [comment]
@amitaibu now i setup the redirect as a first thing today!

**Comment by amitaibu** [comment]
(and #428 will be needed as-well)

**Comment by AronNovak** [comment]
![step-differ1](https://cloud.githubusercontent.com/assets/114076/26538670/81cbb74e-4448-11e7-9ebb-3aacdf649e30.png)
With the redirect and your edit on the application, it seems to be ready.
