### ISSUE TITLE
Change 'X-Frame-Options' header [1h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/productivity#430]
When we try to embed it via IFrame we get `Refused to display 'https://productivity.gizra.com/per-issue/chrome-extension://mmimlickibpigagihcohfhdejiehclnp/frame.html' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by amitaibu** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Need to try `X-Frame-Options: ALLOW-FROM https://github.com`

**Comment by amitaibu** [comment]
@AronNovak https://www.drupal.org/node/2735873

**Comment by AronNovak** [comment]
By hearth, as i remember, it's fixable via `settings.php`, checking in detail now.

**Comment by AronNovak** [comment]
As only in the Pantheon repo, we have the `settings.php`, committing there directly (on dev first).

**Comment by AronNovak** [comment]
![step-differ1](https://cloud.githubusercontent.com/assets/114076/26540338/3a3b9076-4451-11e7-8c57-9964a761f918.png)

Deployed and tested on DEV.

**Comment by AronNovak** [comment]
@amitaibu should i deploy to prod or is there a more sophisticated test (with the extension itself) before that?

**Comment by amitaibu** [comment]
to prod

**Comment by AronNovak** [comment]
![step-differ1](https://cloud.githubusercontent.com/assets/114076/26540713/f7104844-4452-11e7-81a9-a8affd60e059.png)

**Comment by amitaibu** [comment]
That did the trick!

![create_contacts_page_template_display__10h__ _issue__144_ _gizra_municipality](https://cloud.githubusercontent.com/assets/125707/26540826/e028baf4-445b-11e7-8dae-ebaf3132a318.jpg)
