### ISSUE TITLE
Iframe display incorrect actual time

### ISSUE THREAD

**Issue by liatsade** [Gizra/productivity#437]
Issue https://github.com/Gizra/openscholar-huji-hebrew/issues/164
Iframe shows only 3.4h actual time, but in the billing report we see much more hours.

Iframe:
![update_openscholar_core__20h__ _issue__164_ _gizra_openscholar-huji](https://cloud.githubusercontent.com/assets/20393485/26817431/3c0771d2-4a9f-11e7-90cd-be8a1b6e3456.jpg)

Part of the billing report:
![huji_2016_retainer___live_gizra_productivity](https://cloud.githubusercontent.com/assets/20393485/26817401/15369560-4a9f-11e7-9c5a-203749da07e0.jpg)

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/27083486-5ff73df4-5051-11e7-8061-e0939ab46a22.png)

**Comment by bricel** [comment]
@liatsade ^^ - this is what i see.

**Comment by liatsade** [comment]
After re-check the actual time is correct.
