### ISSUE TITLE
Entries auto-generated from Github activity are sometimes on the wrong day

### ISSUE THREAD

**Issue by rgrempel** [Gizra/productivity#439]
The automatically-generated time entries pulled from Github activity are really nice. (That is, when you go to fill in your time, it's really nice that the system has already generated entries based on Github activity).

However, it often happens that the automatic entry is placed on the next day. That is, work I've done on Tuesday is often placed on Wednesday (for example).

My theory is that this is probably because the system isn't taking differing time-zones into account. That is, some of the work which, for me, appears to have been done on Tuesday is, actually, done on Wednesday, since the future arrives earlier for some of us than others.

At least, that would account for anything done by me after 4 PM (subjectively), since that would be the next day in server time.

Though, I'm not sure that's the full explanation, since I don't necessarily do **that** much work after 4 PM -- I could investigate further to see what the precise cut-off appears to be between one day and the next.

**Comment by bricel** [comment]
Your theory sounds right, the time is taken as is from the JSON, probably GMT,  I will check this.

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/26914844-1cc004cc-4c2c-11e7-8065-8b65e18c42b3.png)
This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.

**Comment by bricel** [comment]
Time zones in ISO 8601 are represented as local time (with the location unspecified), as UTC, or as an offset from UTC.

If no UTC relation information is given with a time representation, the time is assumed to be in local time. While it may be safe to assume local time when communicating in the same time zone, it is ambiguous when used in communicating across different time zones. Even within a single geographic time zone, some local times will be ambiguous if the region observes daylight saving time. It is usually preferable to indicate a time zone (zone designator) using the standard's notation.

**Comment by bricel** [comment]
I think the best solution is to keep saving the data using UTC, but just display the user's timezone on the report page.

**Comment by bricel** [comment]
@rgrempel @zarvunk @IshaDakota - On the personal tracking page, the dates are now displayed according to your personal timezone settings, to change the timezone clink on the link marked with the red arrow.

![image](https://user-images.githubusercontent.com/165644/27021719-db88eefe-4f52-11e7-8f4d-ee5bca10a09a.png)

Note: since we didn't take the timezone into consideration until now, all reported hours in the past might be shifted to previous days (if you altered them manually when reporting), this is not an issue since the total amount of hours is the same.

**Comment by bricel** [comment]
@OritGeron ^^ -FYI.

**Comment by rgrempel** [comment]
Thanks, this is very nice -- I adjusted my time zone, and that does seem make things appear on the day I expected.

However, it has introduced one small problem. Now, if I need to make a manual entry (for something that wasn't auto-generated), it always appears on the **previous** day when I save it. That is, if I'm on the page for Wednesday, make a manual entry, and save, the entry now appears on Tuesday instead.

I'm guessing that the manual entries perhaps are given a UTC time that is before 5:00 AM or so? If so, then in my time zone that would appear to be the previous day.

**Comment by IshaDakota** [comment]
^^ same issue

**Comment by bricel** [comment]
@IshaDakota @rgrempel - I pushed a fix today for this.

**Comment by IshaDakota** [comment]
Works as expected.
