### ISSUE TITLE
Time entry recorded to one month shows up at the previous month[1h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/productivity#455]
Time entries:
https://productivity.gizra.com/node/101609/edit
https://productivity.gizra.com/node/101611/edit

Both were recorded under 1st of August.

And the edit page shows accordingly.
But they show up under the summary of July:
![image](https://user-images.githubusercontent.com/114076/28818562-be73c138-76ab-11e7-8f7a-bb0235937e97.png)

It cannot be the timezone configuration, as it's around 11AM, and previous entries from the same day shows up correctly under August.

**Comment by bricel** [comment]
It's a timezone issue:
![image](https://user-images.githubusercontent.com/165644/28819748-deff8098-76b7-11e7-9d82-41754bf403c5.png)

looking into it...

**Comment by bricel** [comment]
@AronNovak - Where those auto generated ? or manual ?

**Comment by RoySegall** [comment]
Got the same thing as well:
![live_gizra_productivity](https://user-images.githubusercontent.com/1222368/28821088-d5a30f4c-76bc-11e7-9569-40d8b2423e20.jpg)

**Comment by AronNovak** [comment]
@bricel i added manually, first, i imagined nothing happened, i re-added them. After deleting them and repeating the process, i got the same result. It happened at two projects, once for Elm Starter, once for JEP.

**Comment by bricel** [comment]
Fixed on live.

**Comment by AronNovak** [comment]
@bricel thanks, i can confirm that my summaries are sane again!
