### ISSUE TITLE
Billing report - print version doesn't show the right date range

### ISSUE THREAD

**Issue by liatsade** [Gizra/productivity#473]
![c4d_phase_3___live_gizra_productivity](https://user-images.githubusercontent.com/20393485/31331858-bea51536-acec-11e7-8687-440951ee7c78.jpg)

![screenshot_09_10_2017__12_24_pm](https://user-images.githubusercontent.com/20393485/31331909-f260483c-acec-11e7-8534-cd886c51a0c8.jpg)

**Comment by OritGeron** [comment]
Closed in lieu of #530
