### ISSUE TITLE
Missing Holiday day

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/productivity#476]
Wednesday is not indicated as a Holiday for Israel employees.

![live_gizra_productivity](https://user-images.githubusercontent.com/14312543/31335391-0fdfdbe4-acfb-11e7-9c19-2727751bb98d.png)

**Comment by OritGeron** [comment]
@bricel can we get that soon?

**Comment by bricel** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/165644/33420191-60190ec6-d5b6-11e7-87c6-19dafe5beb96.png)
