### ISSUE TITLE
Add link to TimeWatch

### ISSUE THREAD

**Issue by liatsade** [Gizra/productivity#490]
Add clock icon (http://fontawesome.io/icon/clock-o/) to the top of the sidebar menu, which links to http://productivity-server.gizra.com/timewatch/ (open in new window).
![live_gizra_productivity](https://user-images.githubusercontent.com/20393485/32990735-54914802-cd37-11e7-8955-cc5c4a7e4975.jpg)

**Comment by liatsade** [comment]
@OritGeron @RachelBaram ^^

**Comment by bricel** [comment]
@liatsade - Can we close ?

**Comment by liatsade** [comment]
yes.
