### ISSUE TITLE
Add in/out indicator

### ISSUE THREAD

**Issue by liatsade** [Gizra/productivity#491]
Add an indication of what I did last (to avoid confusion that makes people report double enter/out).

Lable: Last action
value: in/out (depends on the last user report)

![timewatch](https://user-images.githubusercontent.com/20393485/32990836-1eae4634-cd39-11e7-98b6-38ec9c3870d4.jpg)

**Comment by liatsade** [comment]
@OritGeron @RachelBaram ^^

**Comment by bricel** [comment]
Deployed:
![image](https://user-images.githubusercontent.com/165644/33343723-0800f29e-d48f-11e7-89e7-627d5b83ea48.png)

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/33344167-a8d364a8-d490-11e7-8c1b-906f09b57e56.png)
