### ISSUE TITLE
Add "Status" for each transaction in Payment 

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#494]
![cursor_and_edit_payment_2018_hour_bank___live_gizra_productivity](https://user-images.githubusercontent.com/7068965/33162919-a7bc7b96-d034-11e7-9f2e-b23eb79404a1.png)

**Comment by OritGeron** [comment]
![cursor_and_live_gizra_productivity](https://user-images.githubusercontent.com/7068965/33162994-e9a03520-d034-11e7-87fe-8f5b3cda0c33.png)

**Comment by bricel** [comment]
Why? What should be the statuses ?

**Comment by bricel** [comment]
The transaction is the actual payment, not the entisipation for it.
