### ISSUE TITLE
Change color to red upon punching out of the timewatch

### ISSUE THREAD

**Issue by OritGeron** [Gizra/productivity#496]
![live_gizra_productivity](https://user-images.githubusercontent.com/7068965/33374163-a9737eb6-d50d-11e7-84f9-57c1070ac29b.png)

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/33376223-8ddce5e0-d515-11e7-8fa2-61a8100bd17c.png)

**Comment by OritGeron** [comment]
AWESOME!!

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/33377036-a727b356-d518-11e7-96b9-9a2468c5c173.png)
