### ISSUE TITLE
Weekly [or configurable granularity] summary per project, per developer [3h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/productivity#497]
On advisory contracts for example, it would be nice for the developer, or for the manager, to be able to see per-project, per-developer summary in a weekly granularity.
Right now each developer can see monthly summary, but not weekly.

**Comment by RachelBaram** [comment]
This is important for AM as well!

**Comment by bricel** [comment]
Creating a skeleton PR.

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/33426810-c9d241c4-d5cb-11e7-9121-a5b747cc37ad.png)

**Comment by bricel** [comment]
Done- pushing to pantheon.

**Comment by bricel** [comment]
Forgot to set week start day according to user settings...

**Comment by bricel** [comment]
> Forgot to set week start day according to user settings...

Seems to work out of the box.

**Comment by AronNovak** [comment]
Wonderful, works well 🥇
