### ISSUE TITLE
Move all PR activities from UNICEF advisory to UNICEF

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/productivity#499]
All the PRs (all time) listed under UNICEF advisory should be moved to UNICEF.

cc @IshaDakota

**Comment by RachelBaram** [comment]
@bricel Can you just help me understand if we need to change something in the setup of the project so the migration PR's are not attached to the UNICEF advisory project?

I made the changes myself (one by one):

![tracking_items___live_gizra_productivity](https://user-images.githubusercontent.com/14312543/33523607-ebd050be-d813-11e7-800b-79a6649054dc.png)

![edit_tracking_tracking_for_issue_gizra_global-web-redesign_191___live_gizra_productivity](https://user-images.githubusercontent.com/14312543/33523609-f0be2ec0-d813-11e7-9783-7e04ca018880.png)

**Comment by bricel** [comment]
> Can you just help me understand if we need to change something in the setup of the project so the migration PR's are not attached to the UNICEF advisory project?

You need to make sure the match is unique, right now both prject are marked to be match with same repo.
![image](https://user-images.githubusercontent.com/165644/33523736-8d23af04-d816-11e7-877b-68d474415985.png)

You can do one of the 2:
* Close tracking for the migration.
* Add a milstone to the matching. so it looks for both repo name and milestone for matching.
![image](https://user-images.githubusercontent.com/165644/33523751-c538f62e-d816-11e7-9c1f-86414168eb70.png)

**Comment by RachelBaram** [comment]
We decided that since Migration is going to end this week, we will move the issues to there one by one and then close it.
