### ISSUE TITLE
Add Employee to reports

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/productivity#501]
Add 'employee' to the reports for both the billing and tracking reports (across all types - Mgt,Dev,QA,etc.)

![unicef_-_technical_advisory_burn_table___live_gizra_productivity](https://user-images.githubusercontent.com/14312543/33570480-a108d830-d935-11e7-9272-fbc5cdeb6f56.png)

cc @IshaDakota

**Comment by bricel** [comment]
It's there, just check ``detailed `` checkbox.

**Comment by bricel** [comment]
![image](https://user-images.githubusercontent.com/165644/33599887-423bf244-d9b0-11e7-9b34-ed1aad45feec.png)

**Comment by RachelBaram** [comment]
@IshaDakota Please confirm that the above supports your needs.
