### ISSUE TITLE
Duplicated Milestones Terms on UNFPA 

### ISSUE THREAD

**Issue by noamoss** [Gizra/productivity#523]
Milestone terms are being duplicated for the UNFPA projects when created in GH (PO19, PO20, PO21,PO22) :

![image](https://user-images.githubusercontent.com/3581741/35376729-01925f1c-01b5-11e8-8650-609ed709727b.png)

Please notice we are talking of two separate repositories: UNFPAHQ/unfpa-global, UNFPAHQ/unfpa-offices

**Comment by bricel** [comment]
All seems to be consecutive creating, hence due to race condition. Adding acquire lock to the term creating function.

**Comment by bricel** [comment]
For the existing duplicate term, we need to merge them manually.

**Comment by bricel** [comment]
Duplicated removed.

**Comment by noamoss** [comment]
checked and approved it works:

![image](https://user-images.githubusercontent.com/3581741/35475564-5b07d45a-03a9-11e8-9456-2de3b76edb4c.png)
